version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: yazdrive_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yazdrive_user
      POSTGRES_PASSWORD: yazdrive_password
      POSTGRES_DB: yazdrive_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
